backend:
  name: github
  repo: kenchoreo/debavit-catalog
  branch: main
  base_url: https://debavit-login.kenny070796.workers.dev
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "./assets/uploads"

collections:
  - name: "catalog"
    label: "База товаров"
    files:
      - label: "Все товары"
        name: "products"
        file: "assets/data/products.json" # Все товары будут храниться в этом файле
        fields:
          - label: "Список товаров"
            name: "items"
            widget: "list"
            fields:
              - {label: "ID товара (на англ, без пробелов)", name: "id", widget: "string"}
              - {label: "Название товара", name: "title", widget: "string"}
              - {label: "Главное фото", name: "image", widget: "image"} # Основное фото
              - {label: "Дополнительное фото 1", name: "image2", widget: "image", required: false}
              - {label: "Дополнительное фото 2", name: "image3", widget: "image", required: false}
              - {label: "Описание", name: "description", widget: "text"}
              - {label: "Состав", name: "composition", widget: "text"}
